import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal-page';
export const metadata: Metadata = { title: 'Privacy Policy | Vandlovu Group', description: 'How Vandlovu Group uses and protects your test booking information.' };
export default function Privacy(){return <LegalPage title="Privacy Policy" intro="How we handle the information you share when booking a vehicle test.">
<section><h2>1. Who this policy covers</h2><p>Vandlovu Group operates this vehicle test booking service and is responsible for the booking information collected through it. This policy covers our public booking form, booking updates and administrator portal.</p></section>
<section><h2>2. Information we collect</h2><p>When you request a test, we collect your contact name, company name, phone number, email address, vehicle registration or fleet number, selected test and requested date. We also keep the booking reference, status, timestamps and any rejection reason.</p><p>Our hosting providers may process technical information such as IP addresses, browser details and request logs. The application uses a hashed IP-based identifier and short-lived counters to limit abusive requests. The booking form does not request payment card information or a client account password.</p></section>
<section><h2>3. Why we use your information</h2><p>We use these details to process your request, check availability, arrange testing, approve or reject bookings, communicate changes and protect the service. We process booking information to take steps at your request, provide the service and support legitimate administration and security needs, subject to applicable law. Required form fields are needed to process a booking.</p></section>
<section><h2>4. Who receives it</h2><p>Authorised Vandlovu Group administrators can view booking details. Service providers process information where needed for hosting, database storage and booking email delivery. Depending on the deployment, these include Cloudflare, Vercel, Turso and Google Gmail. Booking information is not displayed in the public availability calendar, and we do not sell it or use it for advertising.</p><p>Providers may process information outside South Africa. Where personal information is transferred internationally, applicable data protection requirements must be observed.</p></section>
<section><h2>5. Google and Gmail</h2><p>Clients do not need to sign in with Google or grant access to their Gmail account. The administrator connects the dedicated booking mailbox using Google OAuth with permission to send email. This connection is used for booking receipts and approval or rejection messages; the application does not read clients’ inboxes or request their Google passwords.</p><p>The mailbox authorisation is held as a server-side credential. The mailbox owner can revoke access in their Google Account permissions. Revocation stops future sending through that connection but does not delete existing booking records or messages already delivered.</p></section>
<section><h2>6. Cookies and security</h2><p>The administrator portal uses an essential, signed session cookie to maintain login for up to 12 hours. The application does not add advertising or analytics cookies. Hosting infrastructure may use additional security cookies. Access controls, password hashing, encrypted connections and request checks help protect information, although no online service can guarantee absolute security.</p></section>
<section><h2>7. Retention</h2><p>Booking records, decisions and email delivery records are retained for booking administration and any applicable recordkeeping obligations. The application does not automatically delete completed bookings. Records should be reviewed and removed or de-identified when no longer needed, unless the law permits or requires continued retention. Short-lived abuse-prevention records are periodically cleared.</p></section>
<section><h2>8. Your choices and rights</h2><p>Subject to South Africa’s Protection of Personal Information Act (POPIA), you may request access to or correction of your personal information, request deletion where appropriate, or object to certain processing. Identity verification may be needed, and legal retention obligations may limit deletion.</p><p>Email <a href="mailto:vandlovugroup@gmail.com">vandlovugroup@gmail.com</a>, quoting your booking reference and explaining your request. You can also raise the request directly with the Vandlovu testing office. Avoid sending unnecessary identity documents or sensitive information.</p><p>You may lodge a complaint with the <a href="https://inforegulator.org.za/popia/" target="_blank" rel="noreferrer">Information Regulator of South Africa</a>.</p></section>
<section><h2>9. Policy updates</h2><p>We may update this policy as the service changes. The date above identifies the current version. Our <a href="/terms">Terms of Service</a> explain the booking process.</p></section>
</LegalPage>}
