'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowLeft, Check, CircleCheck, Clock3, MapPin, CarFront, Truck, Sun, Moon, ShieldCheck, CalendarDays, LoaderCircle, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { SiteHeader, SiteFooter } from './site-header';
import { TESTS, TestId, Availability, dateKey, localDate, saToday, prettyDate } from '@/lib/booking';
function createRequestId(){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
export default function BookingPage(){
 const [selected,setSelected]=useState<TestId>('ldv-brake');const test=TESTS.find(x=>x.id===selected)!;
 const [step,setStep]=useState(1);const [date,setDate]=useState<Date>();const [month,setMonth]=useState(localDate(saToday()));
 const [days,setDays]=useState<Availability[]>([]);const [mode,setMode]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [receipt,setReceipt]=useState<any>(null);const [revision,setRevision]=useState(0);
 const [form,setForm]=useState({contact:'',company:'',phone:'',email:'',vehicle:'',website:''});const requestId=useRef('');const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{requestId.current=createRequestId();},[]);
 useEffect(()=>{let active=true;setLoading(true);setError('');fetch(`/api/availability?month=${dateKey(month).slice(0,7)}&test=${selected}`).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(active){setDays(d.days);setMode(d.mode);}}).catch(e=>{if(active){setDays([]);setError(e.message||'Availability could not be loaded. Please try again.');}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[month,selected,revision]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'select_vehicle_test',title:'Select a vehicle test',description:'Select a test in the booking form. This does not submit a booking.',inputSchema:{type:'object',properties:{testId:{type:'string',enum:TESTS.map(t=>t.id)}},required:['testId'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(!TESTS.some(t=>t.id===input?.testId))throw Error('Unknown test');setSelected(input.testId);setDate(undefined);setStep(1);return {selectedTest:input.testId,bookingSubmitted:false};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 function go(n:number){setStep(n);setError('');setTimeout(()=>heading.current?.focus(),0);}
 async function submit(e:React.FormEvent){e.preventDefault();if(!date)return;setBusy(true);setError('');try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,test:selected,date:dateKey(date),requestId:requestId.current})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setReceipt(d);setRevision(x=>x+1);}catch(e:any){setError(e.message||'Your request could not be submitted. Please try again.');}finally{setBusy(false);}}
 const day=date?days.find(d=>d.date===dateKey(date)):undefined;
 return <><SiteHeader/><main className="booking-main"><div className="page-intro"><div className="eyebrow"><span/> VANDLOVU GROUP · BOOKINGS</div><h1>Let’s get you <span>test-ready.</span></h1><p>Choose your test. Pick a date. We’ll take it from there.</p></div>
 <div className="booking-layout"><section className="booking-workspace">
 {receipt?<div className="receipt"><div className="success-icon"><Check/></div><span className="eyebrow">REQUEST RECEIVED</span><h2>You're on our list.</h2><p>Your booking is <strong>pending approval</strong>. It is not confirmed yet.</p><div className="receipt-reference">REFERENCE <strong>{receipt.reference}</strong></div><dl><div><dt>Test</dt><dd>{test.name}</dd></div><div><dt>Date</dt><dd>{prettyDate(dateKey(date!))}</dd></div><div><dt>Time</dt><dd>{test.time} SAST</dd></div><div><dt>Location</dt><dd>{test.location}</dd></div></dl><p className="notice">{receipt.emailSent?'Your request receipt has been sent by email. We’ll email you again when your request is approved or rejected.':'Your request is saved. Email delivery is not complete; please keep your booking reference.'}</p><Button className="primary-button" onClick={()=>{setReceipt(null);setDate(undefined);setForm({contact:'',company:'',phone:'',email:'',vehicle:'',website:''});requestId.current=createRequestId();go(1);}}>Book another test <ArrowRight/></Button></div>:
 <><ol className="stepper" aria-label="Booking progress">{['Choose a test','Pick a date','Your details'].map((label,i)=><li key={label} className={step===i+1?'current':step>i+1?'complete':''}><button disabled={i+1>step} onClick={()=>go(i+1)} aria-current={step===i+1?'step':undefined}><span>{step>i+1?<Check size={14}/>:String(i+1).padStart(2,'0')}</span>{label}</button></li>)}</ol>
 <div className="step-content"><div className="section-heading"><div><span className="section-kicker">STEP {String(step).padStart(2,'0')}</span><h2 ref={heading} tabIndex={-1}>{step===1?'Which test do you need?':step===2?'Find a day that suits you.':'A few details, and you’re set.'}</h2><p>{step===1?'Select the right test for your vehicle.':step===2?'A maximum of 5 bookings are available per testing day.':'We’ll use these details to manage your booking.'}</p></div><span className="step-count">{step} / 3</span></div>
 {step===1&&<><RadioGroup className="test-grid" value={selected} onValueChange={v=>{setSelected(v as TestId);setDate(undefined);}} aria-label="Vehicle test">{TESTS.map(t=>{const Vehicle=t.category==='LDV'?CarFront:Truck;return <label key={t.id} htmlFor={t.id} className={`test-card ${selected===t.id?'selected':''}`}><div className="test-card-top"><span className="vehicle-icon"><Vehicle size={27} strokeWidth={1.6}/></span><RadioGroupItem id={t.id} value={t.id} className="choice-dot"/></div><div className="test-category">{t.detail}</div><h3>{t.name}</h3><p className="weight">{t.weight}</p><div className="test-meta"><span><MapPin size={14}/>{t.location}</span><span><Clock3 size={14}/>{t.time}{t.id==='hmv-lux'?<Moon size={13}/>:null}</span></div></label>;})}</RadioGroup><div className="step-bottom"><span><ShieldCheck size={17}/> No account needed</span><Button className="primary-button" onClick={()=>go(2)}>Choose a date <ArrowRight/></Button></div></>}
 {step===2&&<><div className="calendar-panel">{loading&&<p className="loading-line"><LoaderCircle className="spin" size={16}/> Checking availability…</p>}<Calendar mode="single" selected={date} onSelect={setDate} month={month} onMonthChange={setMonth} weekStartsOn={1} startMonth={localDate(saToday())} endMonth={new Date(new Date().getFullYear()+1,11,31)} disabled={d=>loading||!days.some(x=>x.date===dateKey(d)&&x.state==='available')} modifiers={{available:days.filter(d=>d.state==='available').map(d=>localDate(d.date)),full:days.filter(d=>d.state==='full').map(d=>localDate(d.date))}} modifiersClassNames={{available:'day-available',full:'day-full'}} className="booking-calendar"/><div className="calendar-legend"><span><i className="available"/>Available</span><span><i className="full"/>Full</span><span><i/>Unavailable</span></div></div>{mode==='unconfigured'&&<p className="notice"><Info size={18}/> Testing dates will be available once the schedule is confirmed.</p>}{date&&day?.state==='available'&&<div className="selected-date"><CalendarDays size={19}/><div><strong>{prettyDate(dateKey(date))}</strong><span>{day.remaining} {day.remaining===1?'space':'spaces'} remaining · {test.time} SAST</span></div></div>}<div className="step-bottom"><Button variant="ghost" onClick={()=>go(1)}><ArrowLeft/> Back</Button><Button className="primary-button" disabled={!date||day?.state!=='available'||loading} onClick={()=>go(3)}>Your details <ArrowRight/></Button></div></>}
 {step===3&&<form onSubmit={submit}><div className="mobile-review"><strong>{test.name}</strong><span>{date?prettyDate(dateKey(date)):""}</span><span>{test.time} SAST · {test.location}</span><span>{test.weight}</span></div><div className="form-grid">{[{id:'contact',label:'Contact person',placeholder:'Full name',auto:'name',type:'text'},{id:'company',label:'Company name',placeholder:'Your company',auto:'organization',type:'text'},{id:'phone',label:'Phone number',placeholder:'e.g. 082 123 4567',auto:'tel',type:'tel'},{id:'email',label:'Email address',placeholder:'you@company.co.za',auto:'email',type:'email'},{id:'vehicle',label:'Vehicle registration / fleet number',placeholder:'e.g. AB 12 CD GP',auto:'off',type:'text'}].map(f=><div className={f.id==='vehicle'?'field full-width':'field'} key={f.id}><Label htmlFor={f.id}>{f.label}</Label><Input id={f.id} required autoComplete={f.auto} type={f.type} maxLength={f.id==='email'?254:120} value={(form as any)[f.id]} placeholder={f.placeholder} onChange={e=>setForm({...form,[f.id]:e.target.value})}/></div>)}</div><div className="trap" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></label></div><p className="notice"><Info size={18}/> This is a booking request. Your test is confirmed only once it has been approved.</p><p className="privacy-note">By submitting, you agree to our <a href="/terms">Terms of Service</a>. Read our <a href="/privacy">Privacy Policy</a> to learn how we use your contact and vehicle details.</p><div className="step-bottom"><Button type="button" variant="ghost" onClick={()=>go(2)}><ArrowLeft/> Back</Button><Button className="primary-button" type="submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:null}{busy?'Submitting…':'Request booking'}<ArrowRight/></Button></div></form>}
 {error&&<div role="alert" className="error-message">{error} {step===2&&<button onClick={()=>setRevision(x=>x+1)}>Try again</button>}</div>}
 </div></>}
 </section><aside className="booking-aside"><div className="summary-card"><span className="summary-kicker">YOUR BOOKING</span><div className="summary-title"><h2>{test.name}</h2>{test.category==='LDV'?<CarFront size={32}/>:<Truck size={32}/>}</div><span className="weight-pill">{test.weight}</span><div className="summary-divider"/><dl><div><dt><MapPin/>LOCATION</dt><dd>{test.location}</dd></div><div><dt><Clock3/>SESSION TIME</dt><dd>{test.time}<small>South African time · SAST</small></dd></div><div><dt><CalendarDays/>TEST DATE</dt><dd>{date?prettyDate(dateKey(date)):<span className="summary-empty">Select your preferred date</span>}</dd></div></dl><div className="summary-note"><ShieldCheck size={21}/><p>Every booking is reviewed.<br/><strong>Confirmation follows approval.</strong></p></div></div><div className="good-to-know"><h3>Before you book</h3><p><CircleCheck/> Choose the category that matches your vehicle’s weight.</p><p><CircleCheck/> Keep your registration or fleet number handy.</p><p><CircleCheck/> Testing runs on selected weekdays only.</p></div></aside></div></main><SiteFooter/></>;
}
