import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal-page';
export const metadata: Metadata = { title: 'Terms of Service | Vandlovu Group', description: 'Terms for requesting and managing vehicle test bookings with Vandlovu Group.' };
export default function Terms(){return <LegalPage title="Terms of Service" intro="Please read these terms before requesting a vehicle test.">
<section><h2>1. Using this service</h2><p>This website lets you request an LDV or HMV brake or lux test with Vandlovu Group. By submitting a request, you agree to these terms and confirm that you are authorised to provide the contact, company and vehicle information entered.</p></section>
<section><h2>2. A request is not a confirmed booking</h2><p>Submitting the form creates a pending request. A reference number or receipt email does not mean your test is approved. Your booking is confirmed only after an authorised administrator approves it. Rejected requests are not confirmed bookings.</p></section>
<section><h2>3. Dates, capacity and times</h2><p>The calendar shows dates available under the current testing schedule. A maximum of five active bookings is shared across all test types per testing day. Pending and approved bookings count towards this limit. Dates may become full or be blocked before a submission completes.</p><p>All dates and session times use South African Standard Time (UTC+02:00). Same-day requests close at the selected session’s start time. Check your test type, vehicle category, date, time and location before submitting and before travelling.</p></section>
<section><h2>4. Accurate information and attendance</h2><p>Provide correct contact and vehicle details and select the appropriate vehicle category. You are responsible for ensuring you can receive booking updates and for following the testing team’s instructions about arrival, vehicle readiness, required documents and site safety. An approved appointment does not guarantee a successful test result or certification.</p></section>
<section><h2>5. Changes, cancellations and fees</h2><p>To change or cancel a request, email <a href="mailto:vandlovugroup@gmail.com">vandlovugroup@gmail.com</a> with your reference. The website does not provide self-service rescheduling or cancellation. Any new date must be confirmed by the testing team.</p><p>This booking form does not collect payment. Confirm applicable testing charges, payment arrangements and any cancellation terms directly with Vandlovu Group before the test. These website terms do not introduce a cancellation charge or replace separately agreed service terms.</p></section>
<section><h2>6. Booking communications</h2><p>Booking receipts and decisions may be sent by email. Delivery may be delayed or fail because of mailbox settings, provider outages or incorrect addresses. Keep your reference and contact the testing team if you have not received a decision. Do not assume approval because no reply has arrived.</p></section>
<section><h2>7. Acceptable use</h2><p>Do not submit false or abusive bookings, impersonate someone else, attempt to access the administrator portal without authorisation, interfere with the service or bypass availability limits. Requests may be limited or declined to protect the service and other users.</p></section>
<section><h2>8. Availability and your rights</h2><p>We aim to keep booking information accurate and the service available, but errors, interruptions and operational changes may occur. Contact Vandlovu Group to resolve a booking issue. Nothing in these terms excludes rights or remedies that cannot lawfully be excluded, including applicable consumer rights.</p></section>
<section><h2>9. Privacy, law and updates</h2><p>Our <a href="/privacy">Privacy Policy</a> explains how we handle booking information. These terms are governed by South African law, subject to any mandatory protections that apply. Updated terms will be published on this page with a revised date.</p></section>
</LegalPage>}
