import {db,runtime} from './server';
import {prettyDate} from './booking';
export function emailReady(){const e=runtime();return !!(e.RESEND_API_KEY&&/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(e.RESEND_FROM||''));}
export function emailText(b:any,kind:string){const status=kind==='receipt'?'Request received — pending approval':b.status==='Approved'?'Booking confirmed':'Booking rejected';const explanation=kind==='receipt'?'Your request is pending approval. This is not a confirmed booking.':b.status==='Approved'?'Your booking has been approved and is confirmed.':'Your booking has been rejected and is not confirmed.';return {subject:`Vandlovu Group | ${status} | ${b.reference}`,text:`Hello ${b.contact},\n\n${explanation}\n\nReference: ${b.reference}\nTest: ${b.test_name}\nVehicle category: ${b.category}\nVehicle / fleet: ${b.vehicle}\nRequested date: ${prettyDate(b.date)}\nTime: ${b.time} (South African Standard Time, UTC+02:00)\nLocation: ${b.location}\n${kind==='decision'&&b.status==='Rejected'?'\nReason: '+b.reason+'\n':''}\nVandlovu Group Bookings`};}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function emailHtml(content:{subject:string;text:string}){return `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(content.subject)}</title></head><body style="margin:0;background:#f4f4f5;color:#18181b;font-family:Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:24px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:auto;background:#fff;border-top:5px solid #dc2626"><tr><td style="padding:28px"><div style="font-size:22px;font-weight:bold;color:#dc2626">VANDLOVU <span style="color:#18181b">GROUP</span></div><div style="margin-top:24px;font-size:16px;line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere">${escapeHtml(content.text)}</div></td></tr></table></td></tr></table></body></html>`;}
export async function sendResend(id:string,to:string,content:{subject:string;text:string},e:Record<string,any>){
 const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${e.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`booking-${id}`},body:JSON.stringify({from:`Vandlovu Group Bookings <${e.RESEND_FROM}>`,to:[to],reply_to:e.RESEND_REPLY_TO?e.RESEND_REPLY_TO.split(',').map((address:string)=>address.trim()).filter(Boolean):undefined,subject:content.subject,text:content.text,html:emailHtml(content)}),signal:AbortSignal.timeout(15000)});
 const result=await response.json().catch(()=>null) as {id?:string}|null;
 if(!response.ok||!result?.id)throw Error(`Resend did not accept this email (HTTP ${response.status}). Check the verified sender and API key, then retry.`);
 return result.id;
}
export async function sendOutbox(id:string){if(!emailReady())return false;const database=db(),now=Date.now();const claim=await database.prepare("UPDATE outbox SET status='sending', lease_until=?, attempts=attempts+1 WHERE id=? AND (status IN ('queued','failed') OR (status='sending' AND lease_until<?)) AND (kind='receipt' OR EXISTS(SELECT 1 FROM outbox o WHERE o.booking_id=outbox.booking_id AND o.kind='receipt' AND o.status='sent')) RETURNING booking_id,kind").bind(now+120000,id,now).first<{booking_id:string;kind:string}>();if(!claim)return !!await database.prepare("SELECT id FROM outbox WHERE id=? AND status='sent'").bind(id).first();
 try{const b:any=await database.prepare('SELECT * FROM bookings WHERE id=?').bind(claim.booking_id).first();const {TESTS}=await import('./booking');b.test_name=TESTS.find(t=>t.id===b.test)?.name||b.test;const content=emailText(b,claim.kind);const e=runtime();await sendResend(id,b.email,content,e);await database.prepare("UPDATE outbox SET status='sent',sent_at=?,error='',lease_until=0 WHERE id=?").bind(new Date().toISOString(),id).run();return true;
 }catch(e){await database.prepare("UPDATE outbox SET status='failed',error=?,lease_until=0 WHERE id=?").bind(e instanceof Error?e.message:'Delivery failed',id).run();return false;}}
export async function deliverBooking(id:string){const messages=await db().prepare("SELECT id FROM outbox WHERE booking_id=? AND status!='sent' ORDER BY CASE kind WHEN 'receipt' THEN 0 ELSE 1 END").bind(id).all<{id:string}>();for(const m of messages.results)await sendOutbox(m.id);}
