import {db,runtime} from './server';
import {prettyDate} from './booking';
export function emailReady(){const e=runtime();return !!(e.GMAIL_CLIENT_ID&&e.GMAIL_CLIENT_SECRET&&e.GMAIL_REFRESH_TOKEN&&/^[^\s@]+@gmail\.com$/i.test(e.GMAIL_SENDER||''));}
export function emailText(b:any,kind:string){const status=kind==='receipt'?'Request received — pending approval':b.status==='Approved'?'Booking confirmed':'Booking rejected';const explanation=kind==='receipt'?'Your request is pending approval. This is not a confirmed booking.':b.status==='Approved'?'Your booking has been approved and is confirmed.':'Your booking has been rejected and is not confirmed.';return {subject:`Vandlovu Group | ${status} | ${b.reference}`,text:`Hello ${b.contact},\n\n${explanation}\n\nReference: ${b.reference}\nTest: ${b.test_name}\nVehicle category: ${b.category}\nVehicle / fleet: ${b.vehicle}\nRequested date: ${prettyDate(b.date)}\nTime: ${b.time} (South African Standard Time, UTC+02:00)\nLocation: ${b.location}\n${kind==='decision'&&b.status==='Rejected'?'\nReason: '+b.reason+'\n':''}\nVandlovu Group Bookings`};}
function b64(s:string){return btoa(String.fromCharCode(...new TextEncoder().encode(s)));}
export async function sendOutbox(id:string){if(!emailReady())return false;const database=db(),now=Date.now();const claim=await database.prepare("UPDATE outbox SET status='sending', lease_until=?, attempts=attempts+1 WHERE id=? AND (status IN ('queued','failed') OR (status='sending' AND lease_until<?)) AND (kind='receipt' OR EXISTS(SELECT 1 FROM outbox o WHERE o.booking_id=outbox.booking_id AND o.kind='receipt' AND o.status='sent')) RETURNING booking_id,kind").bind(now+120000,id,now).first<{booking_id:string;kind:string}>();if(!claim)return !!await database.prepare("SELECT id FROM outbox WHERE id=? AND status='sent'").bind(id).first();
 try{const b:any=await database.prepare('SELECT * FROM bookings WHERE id=?').bind(claim.booking_id).first();const {TESTS}=await import('./booking');b.test_name=TESTS.find(t=>t.id===b.test)?.name||b.test;const content=emailText(b,claim.kind);const e=runtime();const tokenRes=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:e.GMAIL_CLIENT_ID,client_secret:e.GMAIL_CLIENT_SECRET,refresh_token:e.GMAIL_REFRESH_TOKEN,grant_type:'refresh_token'}),signal:AbortSignal.timeout(15000)});const token:any=await tokenRes.json();if(!tokenRes.ok||!token.access_token)throw Error('Gmail connection needs attention');const mime=[`From: Vandlovu Group Bookings <${e.GMAIL_SENDER}>`,`To: ${b.email}`,`Subject: =?UTF-8?B?${b64(content.subject)}?=`,`Message-ID: <${id}@${e.GMAIL_SENDER.split('@')[1]}>`,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',b64(content.text)].join('\r\n');const raw=b64(mime).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const sent=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{Authorization:`Bearer ${token.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({raw}),signal:AbortSignal.timeout(15000)});if(!sent.ok)throw Error('Gmail could not send this message');await database.prepare("UPDATE outbox SET status='sent',sent_at=?,error='',lease_until=0 WHERE id=?").bind(new Date().toISOString(),id).run();return true;
 }catch(e){await database.prepare("UPDATE outbox SET status='failed',error=?,lease_until=0 WHERE id=?").bind(e instanceof Error?e.message:'Delivery failed',id).run();return false;}}
export async function deliverBooking(id:string){const messages=await db().prepare("SELECT id FROM outbox WHERE booking_id=? AND status!='sent' ORDER BY CASE kind WHEN 'receipt' THEN 0 ELSE 1 END").bind(id).all<{id:string}>();for(const m of messages.results)await sendOutbox(m.id);}
