import {body,db,getSettings,json,sameOrigin,rateLimit,safeFailure} from '@/lib/server';
import {TESTS,scheduled,saToday,sessionFuture} from '@/lib/booking';
import {deliverBooking} from '@/lib/email';
import {z} from 'zod';
const text=z.string().trim().min(1).max(120).refine(x=>!/[\r\n\x00-\x1f]/.test(x));
const schema=z.object({requestId:z.string().uuid(),test:z.enum(['ldv-brake','ldv-lux','hmv-brake','hmv-lux']),date:z.string(),contact:text,company:text,phone:z.string().trim().regex(/^\+?[\d ()-]{7,24}$/).refine(x=>x.replace(/\D/g,'').length>=7),email:z.string().trim().email().max(254),vehicle:text,website:z.string().max(0).optional()});
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'Please submit from the booking website.'},403);try{const parsed=schema.safeParse(await body(req));if(!parsed.success)return json({error:'Please check your contact, email, phone and vehicle details.'},400);const v=parsed.data;const existing=await db().prepare('SELECT id,reference FROM bookings WHERE request_id=?').bind(v.requestId).first<{id:string;reference:string}>();if(existing){const sent=!!await db().prepare("SELECT id FROM outbox WHERE booking_id=? AND kind='receipt' AND status='sent'").bind(existing.id).first();return json({reference:existing.reference,status:'Pending',emailSent:sent});}if(!await rateLimit(req,'booking',20,3600))return json({error:'Too many requests. Please try again later.'},429);const settings=await getSettings(),test=TESTS.find(t=>t.id===v.test)!;if(!scheduled(v.date,settings.mode,settings.anchor)||v.date<saToday()||!sessionFuture(v.date,test))return json({error:'That test date is unavailable. Please choose another date.'},409);
const id=crypto.randomUUID(),reference='VD-'+crypto.randomUUID().replace(/-/g,'').slice(0,10).toUpperCase(),now=new Date().toISOString();
try{await db().batch([db().prepare(`INSERT INTO bookings(id,request_id,reference,test,category,date,time,location,contact,company,phone,email,vehicle,status,reason,created_at,updated_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,'Pending','',?,? WHERE EXISTS(SELECT 1 FROM settings WHERE id=1 AND mode=? AND anchor=?) AND NOT EXISTS(SELECT 1 FROM blocks WHERE date=?)`).bind(id,v.requestId,reference,test.id,test.category,v.date,test.time,test.location,v.contact,v.company,v.phone,v.email.toLowerCase(),v.vehicle.toUpperCase(),now,now,settings.mode,settings.anchor,v.date),db().prepare("INSERT INTO outbox(id,booking_id,kind,status,created_at) SELECT ?,id,'receipt','queued',? FROM bookings WHERE id=?").bind(crypto.randomUUID(),now,id)]);}catch(e){if(String(e).includes('booking_capacity')||String(e).includes('date_blocked'))return json({error:'That day has just filled up or become unavailable. Please choose another date.'},409);if(String(e).includes('UNIQUE')){const b=await db().prepare('SELECT reference FROM bookings WHERE request_id=?').bind(v.requestId).first();if(b)return json({...b,status:'Pending',emailSent:false});}throw e;}
if(!await db().prepare('SELECT id FROM bookings WHERE id=?').bind(id).first())return json({error:'Availability changed. Please choose your date again.'},409);await deliverBooking(id);const emailSent=!!await db().prepare("SELECT id FROM outbox WHERE booking_id=? AND kind='receipt' AND status='sent'").bind(id).first();return json({reference,status:'Pending',emailSent},201);
}catch(e){return safeFailure(e);}}
